/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as JobSeekersRouteImport } from './routes/job-seekers'
import { Route as ItServicesProjectsRouteImport } from './routes/it-services-projects'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as C2cContractRouteImport } from './routes/c2c-contract'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTalentAcquisitionRouteImport } from './routes/services.talent-acquisition'
import { Route as ServicesRecruitmentStaffingRouteImport } from './routes/services.recruitment-staffing'
import { Route as ServicesPayrollTaxesRouteImport } from './routes/services.payroll-taxes'
import { Route as ServicesJobPlacementRouteImport } from './routes/services.job-placement'
import { Route as ServicesItTrainingRouteImport } from './routes/services.it-training'
import { Route as ServicesBackgroundVerificationRouteImport } from './routes/services.background-verification'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekersRoute = JobSeekersRouteImport.update({
  id: '/job-seekers',
  path: '/job-seekers',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServicesProjectsRoute = ItServicesProjectsRouteImport.update({
  id: '/it-services-projects',
  path: '/it-services-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const C2cContractRoute = C2cContractRouteImport.update({
  id: '/c2c-contract',
  path: '/c2c-contract',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTalentAcquisitionRoute =
  ServicesTalentAcquisitionRouteImport.update({
    id: '/services/talent-acquisition',
    path: '/services/talent-acquisition',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRecruitmentStaffingRoute =
  ServicesRecruitmentStaffingRouteImport.update({
    id: '/services/recruitment-staffing',
    path: '/services/recruitment-staffing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPayrollTaxesRoute = ServicesPayrollTaxesRouteImport.update({
  id: '/services/payroll-taxes',
  path: '/services/payroll-taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesJobPlacementRoute = ServicesJobPlacementRouteImport.update({
  id: '/services/job-placement',
  path: '/services/job-placement',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesItTrainingRoute = ServicesItTrainingRouteImport.update({
  id: '/services/it-training',
  path: '/services/it-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBackgroundVerificationRoute =
  ServicesBackgroundVerificationRouteImport.update({
    id: '/services/background-verification',
    path: '/services/background-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/c2c-contract': typeof C2cContractRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/it-services-projects': typeof ItServicesProjectsRoute
  '/job-seekers': typeof JobSeekersRoute
  '/referral': typeof ReferralRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/background-verification': typeof ServicesBackgroundVerificationRoute
  '/services/it-training': typeof ServicesItTrainingRoute
  '/services/job-placement': typeof ServicesJobPlacementRoute
  '/services/payroll-taxes': typeof ServicesPayrollTaxesRoute
  '/services/recruitment-staffing': typeof ServicesRecruitmentStaffingRoute
  '/services/talent-acquisition': typeof ServicesTalentAcquisitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/c2c-contract': typeof C2cContractRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/it-services-projects': typeof ItServicesProjectsRoute
  '/job-seekers': typeof JobSeekersRoute
  '/referral': typeof ReferralRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/background-verification': typeof ServicesBackgroundVerificationRoute
  '/services/it-training': typeof ServicesItTrainingRoute
  '/services/job-placement': typeof ServicesJobPlacementRoute
  '/services/payroll-taxes': typeof ServicesPayrollTaxesRoute
  '/services/recruitment-staffing': typeof ServicesRecruitmentStaffingRoute
  '/services/talent-acquisition': typeof ServicesTalentAcquisitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/c2c-contract': typeof C2cContractRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/it-services-projects': typeof ItServicesProjectsRoute
  '/job-seekers': typeof JobSeekersRoute
  '/referral': typeof ReferralRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/background-verification': typeof ServicesBackgroundVerificationRoute
  '/services/it-training': typeof ServicesItTrainingRoute
  '/services/job-placement': typeof ServicesJobPlacementRoute
  '/services/payroll-taxes': typeof ServicesPayrollTaxesRoute
  '/services/recruitment-staffing': typeof ServicesRecruitmentStaffingRoute
  '/services/talent-acquisition': typeof ServicesTalentAcquisitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/c2c-contract'
    | '/contact'
    | '/employers'
    | '/it-services-projects'
    | '/job-seekers'
    | '/referral'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/background-verification'
    | '/services/it-training'
    | '/services/job-placement'
    | '/services/payroll-taxes'
    | '/services/recruitment-staffing'
    | '/services/talent-acquisition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/c2c-contract'
    | '/contact'
    | '/employers'
    | '/it-services-projects'
    | '/job-seekers'
    | '/referral'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/background-verification'
    | '/services/it-training'
    | '/services/job-placement'
    | '/services/payroll-taxes'
    | '/services/recruitment-staffing'
    | '/services/talent-acquisition'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/c2c-contract'
    | '/contact'
    | '/employers'
    | '/it-services-projects'
    | '/job-seekers'
    | '/referral'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services/background-verification'
    | '/services/it-training'
    | '/services/job-placement'
    | '/services/payroll-taxes'
    | '/services/recruitment-staffing'
    | '/services/talent-acquisition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  C2cContractRoute: typeof C2cContractRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  ItServicesProjectsRoute: typeof ItServicesProjectsRoute
  JobSeekersRoute: typeof JobSeekersRoute
  ReferralRoute: typeof ReferralRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesBackgroundVerificationRoute: typeof ServicesBackgroundVerificationRoute
  ServicesItTrainingRoute: typeof ServicesItTrainingRoute
  ServicesJobPlacementRoute: typeof ServicesJobPlacementRoute
  ServicesPayrollTaxesRoute: typeof ServicesPayrollTaxesRoute
  ServicesRecruitmentStaffingRoute: typeof ServicesRecruitmentStaffingRoute
  ServicesTalentAcquisitionRoute: typeof ServicesTalentAcquisitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seekers': {
      id: '/job-seekers'
      path: '/job-seekers'
      fullPath: '/job-seekers'
      preLoaderRoute: typeof JobSeekersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-services-projects': {
      id: '/it-services-projects'
      path: '/it-services-projects'
      fullPath: '/it-services-projects'
      preLoaderRoute: typeof ItServicesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c2c-contract': {
      id: '/c2c-contract'
      path: '/c2c-contract'
      fullPath: '/c2c-contract'
      preLoaderRoute: typeof C2cContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/talent-acquisition': {
      id: '/services/talent-acquisition'
      path: '/services/talent-acquisition'
      fullPath: '/services/talent-acquisition'
      preLoaderRoute: typeof ServicesTalentAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/recruitment-staffing': {
      id: '/services/recruitment-staffing'
      path: '/services/recruitment-staffing'
      fullPath: '/services/recruitment-staffing'
      preLoaderRoute: typeof ServicesRecruitmentStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/payroll-taxes': {
      id: '/services/payroll-taxes'
      path: '/services/payroll-taxes'
      fullPath: '/services/payroll-taxes'
      preLoaderRoute: typeof ServicesPayrollTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/job-placement': {
      id: '/services/job-placement'
      path: '/services/job-placement'
      fullPath: '/services/job-placement'
      preLoaderRoute: typeof ServicesJobPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-training': {
      id: '/services/it-training'
      path: '/services/it-training'
      fullPath: '/services/it-training'
      preLoaderRoute: typeof ServicesItTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/background-verification': {
      id: '/services/background-verification'
      path: '/services/background-verification'
      fullPath: '/services/background-verification'
      preLoaderRoute: typeof ServicesBackgroundVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  C2cContractRoute: C2cContractRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  ItServicesProjectsRoute: ItServicesProjectsRoute,
  JobSeekersRoute: JobSeekersRoute,
  ReferralRoute: ReferralRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesBackgroundVerificationRoute: ServicesBackgroundVerificationRoute,
  ServicesItTrainingRoute: ServicesItTrainingRoute,
  ServicesJobPlacementRoute: ServicesJobPlacementRoute,
  ServicesPayrollTaxesRoute: ServicesPayrollTaxesRoute,
  ServicesRecruitmentStaffingRoute: ServicesRecruitmentStaffingRoute,
  ServicesTalentAcquisitionRoute: ServicesTalentAcquisitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
